on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Deploy 
jobs:
  build:
      name: Deploying to app service
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v1


        - name: Azure login
          env:
            azure_username: ${{secrets.AZURE_USERNAME}}
            azure_password: ${{secrets.AZURE_PASSWORD}}
          run: |
               az login -u $azure_username -p $azure_password
        - name: ACR login
          env:
            container_registry_url: ${{secrets.CONTAINER_REGISTRY_URL}}
            acr_username: ${{secrets.ACR_USERNAME}}
            acr_password: ${{secrets.ACR_PASSWORD}}
          run: |
               docker login $container_registry_url --username $acr_username --password $acr_password
        - name: Installing webpack
          run: |
               npm install --save-dev webpack
        - name: Containerizing in progress
          env:
            name_for_docker_image: ${{secrets.NAME_FOR_DOCKER_IMAGE}}
            docker_file_location: ${{ secrets.DOCKER_FILE_LOCATION }}
          run: |
               docker build --tag $name_for_docker_image $docker_file_location
        - name: Tagging image
          env:
            name_for_docker_image: ${{secrets.NAME_FOR_DOCKER_IMAGE}}
            container_registry_url: ${{secrets.CONTAINER_REGISTRY_URL}}
          run: |
               docker tag $name_for_docker_image $container_registry_url/$name_for_docker_image:latest
        - name: Pushing image to ACR
          env:
            container_registry_url: ${{secrets.CONTAINER_REGISTRY_URL}}
            name_for_docker_image: ${{secrets.NAME_FOR_DOCKER_IMAGE}}
          run: |
               docker push $container_registry_url/$name_for_docker_image:latest

        - if: "true"
          run: echo "Conatiner exists"
